package com.spring.mybatis02.modelEx;

public class MybatisMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.MYBATIS_MEMBER.ID
     *
     * @mbg.generated Fri May 21 16:46:37 KST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.MYBATIS_MEMBER.PWD
     *
     * @mbg.generated Fri May 21 16:46:37 KST 2021
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.MYBATIS_MEMBER.NAME
     *
     * @mbg.generated Fri May 21 16:46:37 KST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.MYBATIS_MEMBER.TEL
     *
     * @mbg.generated Fri May 21 16:46:37 KST 2021
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.MYBATIS_MEMBER.EMAIL
     *
     * @mbg.generated Fri May 21 16:46:37 KST 2021
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.MYBATIS_MEMBER.ID
     *
     * @return the value of HR.MYBATIS_MEMBER.ID
     *
     * @mbg.generated Fri May 21 16:46:37 KST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.MYBATIS_MEMBER.ID
     *
     * @param id the value for HR.MYBATIS_MEMBER.ID
     *
     * @mbg.generated Fri May 21 16:46:37 KST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.MYBATIS_MEMBER.PWD
     *
     * @return the value of HR.MYBATIS_MEMBER.PWD
     *
     * @mbg.generated Fri May 21 16:46:37 KST 2021
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.MYBATIS_MEMBER.PWD
     *
     * @param pwd the value for HR.MYBATIS_MEMBER.PWD
     *
     * @mbg.generated Fri May 21 16:46:37 KST 2021
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.MYBATIS_MEMBER.NAME
     *
     * @return the value of HR.MYBATIS_MEMBER.NAME
     *
     * @mbg.generated Fri May 21 16:46:37 KST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.MYBATIS_MEMBER.NAME
     *
     * @param name the value for HR.MYBATIS_MEMBER.NAME
     *
     * @mbg.generated Fri May 21 16:46:37 KST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.MYBATIS_MEMBER.TEL
     *
     * @return the value of HR.MYBATIS_MEMBER.TEL
     *
     * @mbg.generated Fri May 21 16:46:37 KST 2021
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.MYBATIS_MEMBER.TEL
     *
     * @param tel the value for HR.MYBATIS_MEMBER.TEL
     *
     * @mbg.generated Fri May 21 16:46:37 KST 2021
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.MYBATIS_MEMBER.EMAIL
     *
     * @return the value of HR.MYBATIS_MEMBER.EMAIL
     *
     * @mbg.generated Fri May 21 16:46:37 KST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.MYBATIS_MEMBER.EMAIL
     *
     * @param email the value for HR.MYBATIS_MEMBER.EMAIL
     *
     * @mbg.generated Fri May 21 16:46:37 KST 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }
}